package ostis.jesc.memory.element.edge

import ostis.jesc.client.model.type.ScType
import ostis.jesc.memory.element.ScSpecificType

enum class ScEdgeType(override val type: ScType): ScSpecificType {
    U_COMMON(ScType.EDGE_U_COMMON),
    D_COMMON(ScType.EDGE_D_COMMON),
    U_COMMON_CONST(ScType.EDGE_U_COMMON_CONST),
    D_COMMON_CONST(ScType.EDGE_D_COMMON_CONST),
    U_COMMON_VAR(ScType.EDGE_U_COMMON_VAR),
    D_COMMON_VAR(ScType.EDGE_D_COMMON_VAR),
    ACCESS(ScType.EDGE_ACCESS),
    ACCESS_CONST_POS_PERM(ScType.EDGE_ACCESS_CONST_POS_PERM),
    ACCESS_CONST_NEG_PERM(ScType.EDGE_ACCESS_CONST_NEG_PERM),
    ACCESS_CONST_FUZ_PERM(ScType.EDGE_ACCESS_CONST_FUZ_PERM),
    ACCESS_CONST_POS_TEMP(ScType.EDGE_ACCESS_CONST_POS_TEMP),
    ACCESS_CONST_NEG_TEMP(ScType.EDGE_ACCESS_CONST_NEG_TEMP),
    ACCESS_CONST_FUZ_TEMP(ScType.EDGE_ACCESS_CONST_FUZ_TEMP),
    ACCESS_VAR_POS_PERM(ScType.EDGE_ACCESS_VAR_POS_PERM),
    ACCESS_VAR_NEG_PERM(ScType.EDGE_ACCESS_VAR_NEG_PERM),
    ACCESS_VAR_FUZ_PERM(ScType.EDGE_ACCESS_VAR_FUZ_PERM),
    ACCESS_VAR_POS_TEMP(ScType.EDGE_ACCESS_VAR_POS_TEMP),
    ACCESS_VAR_NEG_TEMP(ScType.EDGE_ACCESS_VAR_NEG_TEMP),
    ACCESS_VAR_FUZ_TEMP(ScType.EDGE_ACCESS_VAR_FUZ_TEMP)
}